title = "Brady Madden"

publishDir = "public"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
# googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
# disqusShortname = "bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "favicon.png" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = ["css/main.css"]
  js_modules = ["js/main.js"]

  # Description and meta data for the search engines
  author = "Brady Madden"
  description = "Brady Madden's personal website and blog."
  # keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 5

  # Enable / Disable MathJax
  enable_mathjax    = true

  # Header configuration
	
	currentLocation = "Copenhagen, Denmark"

    # if you want to use gravatar for the header image
    gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "/images/bradyheader190x190.jpg"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

  # social media profile urls for the footer links
  email   = "mailto:bhm3mr@virginia.edu"
  facebook  = "https://facebook.com/brady.madden.98"
  github     = "https://github.com/bradymadden97"
  linkedin    = "https://linkedin.com/in/bradyhmadden"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
